[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "DEFAULT_EMAIL_DOMAIN,DEFAULT_VIDEO_MAX_SIZE,DEFAULT_DOC_MAX_SIZE,DEFAULT_ZIP_MAX_SIZE,NEXT_PUBLIC_FILE_URL,NEXTAUTH_URL,RESEND_FROM_EMAIL,NEXT_PUBLIC_APP_URL,APP_URL,NEXT_PUBLIC_DEFAULT_EMAIL_DOMAIN,SUPABASE_URL,SUPABASE_URL_1,SUPABASE_URL_2,SUPABASE_URL_3,SUPABASE_URL_4,SUPABASE_URL_5,SUPABASE_ANON_KEY,SUPABASE_ANON_KEY_1,SUPABASE_ANON_KEY_2,SUPABASE_ANON_KEY_3,SUPABASE_ANON_KEY_4,SUPABASE_ANON_KEY_5"
